# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# on: workflow_dispatch
# #  push:
# #   branches: [master]
# #pull_request:
# # branches: [master]

on:
  workflow_dispatch:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Checking node and npm version
        run: |
          node -v
          npm -v
      - name: Installing Packages
        run: |
          npm install
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: ${{secrets.DB_URL}}
          path: ${{secrets.BACKUP_PATH}}
          options: "-O"
      - name: Starting the Node File
        run: node src/helpers/discordWebhook.ts
        env:
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
          BACKUP_PATH: ${{secrets.BACKUP_PATH}}
